export const data = {
  nodes: [
    { id: "google", group: 1 },
    { id: "facebook", group: 1 },
    { id: "medium", group: 2 },
    { id: "someBlog", group: 2 },
    { id: "someotherBlog", group: 3 },
    { id: "instagram", group: 2 },
    { id: "linkedin", group: 3 },
    { id: "twitter", group: 1 },
    { id: "snapchat", group: 3 },
    { id: "twitch", group: 3 },
  ],
  links: [
    { source: "twitch", target: "google", value: 1 },
    { source: "google", target: "instagram", value: 8 },
    { source: "instagram", target: "facebook", value: 10 },
    { source: "twitter", target: "linkedin", value: 6 },
    { source: "google", target: "snapchat", value: 1 },
    { source: "facebook", target: "snapchat", value: 2 },
    { source: "instagram", target: "twitch", value: 3 },
    { source: "google", target: "twitter", value: 1 },
    { source: "medium", target: "google", value: 5 },
    { source: "google", target: "twitch", value: 7 },
    { source: "someBlog", target: "someotherBlog", value: 2 },
    { source: "someBlog", target: "twitch", value: 13 },
    { source: "snapchat", target: "instagram", value: 2 },
    { source: "someBlog", target: "linkedin", value: 6 },
  ],
};
